services:
  userManagement:
    image: bytesized-journey-user-management:${BYTESIZED_JOURNEY_VERSION}
    build:
      context: ./src/userManagement
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./src/userManagement/.env
  userManagementDatabase:
    image: postgres:14.17-bookworm
    ports:
      - "5432:5432"
    env_file:
      - ./src/userManagement/.env
    volumes:
      - userManagement:/var/lib/postgresql/data
      - ./src/userManagement/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
volumes:
  userManagement: